version: "3.5"

services:
    main:
        image: jwilder/whoami
        networks:
            - caddy-net

    main-api:
        image: jwilder/whoami
        networks:
            - caddy-net

    sub:
        image: jwilder/whoami
        networks:
            - caddy-net

networks:
    caddy-net:
        external: true