version: "3.8"

services:
    haproxy:
        image: haproxy:2.1
        container_name: haproxy
        ports:
            - 80:80
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

networks:
    default:
        name: haproxy-net
