version: "3.5"

services:
    main:
        image: jwilder/whoami
        networks:
            - haproxy-net

    main-api:
        image: jwilder/whoami
        networks:
            - haproxy-net

    sub:
        image: jwilder/whoami
        networks:
            - haproxy-net

networks:
    haproxy-net:
        external: true
